/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/pages/LoginPage.tsx', './src/styles/LoginPage.css'],
  darkMode: 'class',
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        outline: '#767680',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#616363',
        'surface-container-low': '#eff4ff',
        tertiary: '#000000',
        'surface-bright': '#f8f9ff',
        'surface-container': '#e5eeff',
        'secondary-fixed': '#e2e2e2',
        'surface-container-high': '#dce9ff',
        'on-tertiary-container': '#81848a',
        'outline-variant': '#c6c5d0',
        'inverse-primary': '#bac4f8',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#0d1843',
        'surface-container-highest': '#d3e4fe',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#c4c6cd',
        'secondary-container': '#dfe0e0',
        'primary-fixed-dim': '#bac4f8',
        'primary-fixed': '#dde1ff',
        secondary: '#5d5f5f',
        'on-primary-fixed': '#0d1843',
        'surface-dim': '#cbdbf5',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#c6c6c7',
        'surface-variant': '#d3e4fe',
        primary: '#000000',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#181c21',
        surface: '#f8f9ff',
        'on-surface': '#0b1c30',
        'inverse-on-surface': '#eaf1ff',
        'on-tertiary-fixed-variant': '#44474c',
        'on-secondary-fixed-variant': '#454747',
        error: '#ba1a1a',
        'tertiary-fixed': '#e0e2e9',
        background: '#f8f9ff',
        'surface-tint': '#525c8a',
        'tertiary-container': '#181c21',
        'on-secondary-fixed': '#1a1c1c',
        'on-primary-fixed-variant': '#3a4471',
        'on-primary-container': '#7881b2',
        'inverse-surface': '#213145',
        'error-container': '#ffdad6',
        'on-surface-variant': '#45464f',
        'on-background': '#0b1c30',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        'margin-mobile': '20px',
        gutter: '24px',
        'max-width': '1280px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Hanken Grotesk'],
        'display-lg': ['Hanken Grotesk'],
        'body-lg': ['Inter'],
        'headline-lg': ['Hanken Grotesk'],
        'body-md': ['Inter'],
        'headline-md': ['Hanken Grotesk'],
        'label-sm': ['JetBrains Mono'],
        'label-md': ['JetBrains Mono'],
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'display-lg': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' },
        ],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': [
          '14px',
          { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' },
        ],
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.45s ease-out',
      },
    },
  },
  plugins: [],
};
