ALTER TABLE delegation_log
    ADD COLUMN approval_required BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN student_approval_expires_at TIMESTAMP(6),
    ADD COLUMN target_slot_id INTEGER,
    ADD COLUMN target_slot_date DATE,
    ADD COLUMN target_start_time TIME(6),
    ADD COLUMN target_end_time TIME(6),
    ADD COLUMN slot_lock_status VARCHAR(32);

ALTER TABLE delegation_log
    ADD CONSTRAINT fk_delegation_target_slot
        FOREIGN KEY (target_slot_id) REFERENCES availability_slot (slot_id);

CREATE INDEX idx_delegation_active_slot_lock
    ON delegation_log (delegated_to_user_id, target_slot_date, target_start_time, target_end_time, slot_lock_status);

CREATE TABLE notification (
    notification_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               INTEGER NOT NULL,
    notification_type     VARCHAR(64) NOT NULL,
    title                 VARCHAR(255) NOT NULL,
    message               VARCHAR(1000) NOT NULL,
    related_delegation_id INTEGER,
    is_read               BOOLEAN NOT NULL DEFAULT FALSE,
    email_delivery_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    recipient_email       VARCHAR(255) NOT NULL,
    created_at            TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_notification_user
        FOREIGN KEY (user_id) REFERENCES "user" (user_id),
    CONSTRAINT fk_notification_delegation
        FOREIGN KEY (related_delegation_id) REFERENCES delegation_log (delegation_id)
);

CREATE INDEX idx_notification_user_created
    ON notification (user_id, created_at DESC);
