CREATE TABLE appointment_reschedule_request (
    reschedule_request_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id        INTEGER NOT NULL,
    original_slot_id      INTEGER NOT NULL,
    proposed_slot_id      INTEGER NOT NULL,
    proposed_meeting_type VARCHAR(32) NOT NULL,
    request_status        VARCHAR(32) NOT NULL,
    expires_at            TIMESTAMP(6) NOT NULL,
    created_at            TIMESTAMP(6) NOT NULL,
    updated_at            TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_reschedule_appointment FOREIGN KEY (appointment_id) REFERENCES appointment (appointment_id),
    CONSTRAINT fk_reschedule_original_slot FOREIGN KEY (original_slot_id) REFERENCES availability_slot (slot_id),
    CONSTRAINT fk_reschedule_proposed_slot FOREIGN KEY (proposed_slot_id) REFERENCES availability_slot (slot_id)
);

CREATE INDEX idx_reschedule_pending_expiry
    ON appointment_reschedule_request (request_status, expires_at);

CREATE INDEX idx_reschedule_proposed_slot
    ON appointment_reschedule_request (proposed_slot_id, request_status, expires_at);

CREATE UNIQUE INDEX uq_reschedule_pending_appointment
    ON appointment_reschedule_request (appointment_id)
    WHERE request_status = 'PENDING';
