CREATE TABLE appointment_reminder_delivery (
    reminder_delivery_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id       INTEGER NOT NULL,
    recipient_user_id    INTEGER NOT NULL,
    reminder_type        VARCHAR(32) NOT NULL,
    delivery_status      VARCHAR(16) NOT NULL,
    attempted_at         TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_appointment_reminder_delivery
        UNIQUE (appointment_id, recipient_user_id, reminder_type),
    CONSTRAINT fk_reminder_delivery_appointment
        FOREIGN KEY (appointment_id) REFERENCES appointment (appointment_id),
    CONSTRAINT fk_reminder_delivery_recipient
        FOREIGN KEY (recipient_user_id) REFERENCES "user" (user_id)
);

CREATE INDEX idx_appointment_reminder_delivery_appointment
    ON appointment_reminder_delivery (appointment_id);

CREATE INDEX idx_appointment_status
    ON appointment (appointment_status);

CREATE INDEX idx_availability_slot_date_time
    ON availability_slot (slot_date, start_time);
