-- MARS initial schema (ER + Veri Sözlüğü)

CREATE TABLE role (
    role_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name       VARCHAR(255) NOT NULL
);

CREATE TABLE department (
    department_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(255) NOT NULL
);

CREATE TABLE appointment_category (
    category_id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name             VARCHAR(255) NOT NULL,
    duration_minutes          INTEGER NOT NULL,
    category_group            VARCHAR(255) NOT NULL,
    requires_course_selection BOOLEAN NOT NULL
);

CREATE TABLE penalty_rule (
    penalty_rule_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    max_no_show_count  INTEGER NOT NULL,
    ban_duration_days  INTEGER NOT NULL,
    is_active          BOOLEAN NOT NULL
);

CREATE TABLE "user" (
    user_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name            VARCHAR(255) NOT NULL,
    institutional_email  VARCHAR(255) NOT NULL,
    password_hash        VARCHAR(255) NOT NULL,
    role_id              INTEGER NOT NULL,
    department_id        INTEGER NOT NULL,
    is_active            BOOLEAN NOT NULL,
    created_at           TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_user_institutional_email UNIQUE (institutional_email),
    CONSTRAINT fk_user_role
        FOREIGN KEY (role_id) REFERENCES role (role_id),
    CONSTRAINT fk_user_department
        FOREIGN KEY (department_id) REFERENCES department (department_id)
);

CREATE TABLE course (
    course_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code            VARCHAR(255) NOT NULL,
    course_name            VARCHAR(255) NOT NULL,
    department_id          INTEGER NOT NULL,
    academic_term          VARCHAR(255) NOT NULL,
    owner_academician_id   INTEGER NOT NULL,
    CONSTRAINT fk_course_department
        FOREIGN KEY (department_id) REFERENCES department (department_id),
    CONSTRAINT fk_course_owner_academician
        FOREIGN KEY (owner_academician_id) REFERENCES "user" (user_id)
);

CREATE TABLE course_assignment (
    course_assignment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id            INTEGER NOT NULL,
    assistant_id         INTEGER NOT NULL,
    assigned_at          TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_course_assignment_course
        FOREIGN KEY (course_id) REFERENCES course (course_id),
    CONSTRAINT fk_course_assignment_assistant
        FOREIGN KEY (assistant_id) REFERENCES "user" (user_id)
);

CREATE TABLE recurrence_rule (
    recurrence_rule_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id           INTEGER NOT NULL,
    repeat_type        VARCHAR(255) NOT NULL,
    repeat_count       INTEGER NOT NULL,
    start_date         DATE NOT NULL,
    end_date           DATE NOT NULL,
    CONSTRAINT fk_recurrence_rule_staff
        FOREIGN KEY (staff_id) REFERENCES "user" (user_id)
);

CREATE TABLE availability_slot (
    slot_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id           INTEGER NOT NULL,
    slot_date          DATE NOT NULL,
    start_time         TIME(6) NOT NULL,
    end_time           TIME(6) NOT NULL,
    recurrence_rule_id INTEGER,
    is_blocked         BOOLEAN NOT NULL,
    CONSTRAINT fk_availability_slot_staff
        FOREIGN KEY (staff_id) REFERENCES "user" (user_id),
    CONSTRAINT fk_availability_slot_recurrence_rule
        FOREIGN KEY (recurrence_rule_id) REFERENCES recurrence_rule (recurrence_rule_id)
);

CREATE TABLE out_of_office_period (
    out_of_office_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id         INTEGER NOT NULL,
    start_date       DATE NOT NULL,
    end_date         DATE NOT NULL,
    reason_code      VARCHAR(255) NOT NULL,
    CONSTRAINT fk_out_of_office_period_staff
        FOREIGN KEY (staff_id) REFERENCES "user" (user_id)
);

CREATE TABLE appointment (
    appointment_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id                 INTEGER NOT NULL,
    staff_id                   INTEGER NOT NULL,
    category_id                INTEGER NOT NULL,
    course_id                  INTEGER,
    slot_id                    INTEGER NOT NULL,
    appointment_status         VARCHAR(255) NOT NULL,
    is_limited_duration        BOOLEAN NOT NULL,
    no_show_marked_by_user_id  INTEGER,
    created_at                 TIMESTAMP(6) NOT NULL,
    updated_at                 TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_appointment_slot_id UNIQUE (slot_id),
    CONSTRAINT fk_appointment_student
        FOREIGN KEY (student_id) REFERENCES "user" (user_id),
    CONSTRAINT fk_appointment_staff
        FOREIGN KEY (staff_id) REFERENCES "user" (user_id),
    CONSTRAINT fk_appointment_category
        FOREIGN KEY (category_id) REFERENCES appointment_category (category_id),
    CONSTRAINT fk_appointment_course
        FOREIGN KEY (course_id) REFERENCES course (course_id),
    CONSTRAINT fk_appointment_slot
        FOREIGN KEY (slot_id) REFERENCES availability_slot (slot_id),
    CONSTRAINT fk_appointment_no_show_marked_by_user
        FOREIGN KEY (no_show_marked_by_user_id) REFERENCES "user" (user_id)
);

CREATE TABLE delegation_log (
    delegation_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id        INTEGER NOT NULL,
    delegated_by_user_id  INTEGER NOT NULL,
    delegated_to_user_id  INTEGER NOT NULL,
    delegated_at          TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_delegation_log_appointment
        FOREIGN KEY (appointment_id) REFERENCES appointment (appointment_id),
    CONSTRAINT fk_delegation_log_delegated_by_user
        FOREIGN KEY (delegated_by_user_id) REFERENCES "user" (user_id),
    CONSTRAINT fk_delegation_log_delegated_to_user
        FOREIGN KEY (delegated_to_user_id) REFERENCES "user" (user_id)
);

CREATE TABLE student_penalty_status (
    student_id               INTEGER PRIMARY KEY,
    is_restricted            BOOLEAN NOT NULL,
    restriction_start_date   DATE,
    restriction_end_date     DATE,
    total_no_show_count      INTEGER NOT NULL,
    penalty_rule_id          INTEGER NOT NULL,
    CONSTRAINT fk_student_penalty_status_student
        FOREIGN KEY (student_id) REFERENCES "user" (user_id),
    CONSTRAINT fk_student_penalty_status_penalty_rule
        FOREIGN KEY (penalty_rule_id) REFERENCES penalty_rule (penalty_rule_id)
);

CREATE TABLE waitlist_entry (
    waitlist_entry_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id        INTEGER NOT NULL,
    staff_id          INTEGER NOT NULL,
    category_id       INTEGER NOT NULL,
    course_id         INTEGER,
    requested_at      TIMESTAMP(6) NOT NULL,
    waitlist_status   VARCHAR(255) NOT NULL,
    CONSTRAINT fk_waitlist_entry_student
        FOREIGN KEY (student_id) REFERENCES "user" (user_id),
    CONSTRAINT fk_waitlist_entry_staff
        FOREIGN KEY (staff_id) REFERENCES "user" (user_id),
    CONSTRAINT fk_waitlist_entry_category
        FOREIGN KEY (category_id) REFERENCES appointment_category (category_id),
    CONSTRAINT fk_waitlist_entry_course
        FOREIGN KEY (course_id) REFERENCES course (course_id)
);
