@startuml

left to right direction

skinparam shadowing false
skinparam nodesep 15
skinparam ranksep 12
skinparam defaultTextAlignment center
skinparam actor {
    FontSize 20
    BorderThickness 1.5
}
skinparam usecase {
    BackgroundColor White
    BorderColor Black
    FontSize 10
    Padding 2
}

actor "Admin" as Admin

usecase "Sisteme Giriş Yap" as ADM_UC01
usecase "Şifre Sıfırla" as ADM_UC02
usecase "Çıkış Yap" as ADM_UC20
usecase "Ana Ekranı\nGörüntüle" as ADM_UC03
usecase "Kullanıcıları\nGörüntüle" as ADM_UC04
usecase "Kullanıcı Oluştur" as ADM_UC05
usecase "Kullanıcı Güncelle" as ADM_UC06
usecase "Kullanıcı Durumu\nDeğiştir" as ADM_UC07
usecase "Kategorileri\nGörüntüle" as ADM_UC08
usecase "Kategori Oluştur" as ADM_UC09
usecase "Kategori Güncelle" as ADM_UC10
usecase "Kategori Sil" as ADM_UC11
usecase "Ceza Kuralını\nGörüntüle" as ADM_UC12
usecase "Ceza Kuralını\nGüncelle" as ADM_UC13
usecase "Scheduler Durumunu\nGörüntüle" as ADM_UC14
usecase "Profil Görüntüle" as ADM_UC15
usecase "Şifre Değiştir" as ADM_UC16
usecase "E-Posta Bildirim\nTercihlerini Güncelle" as ADM_UC17
usecase "Bildirimleri\nGörüntüle" as ADM_UC18
usecase "Bildirimleri Okundu\nİşaretle" as ADM_UC19

Admin -- ADM_UC03
Admin -- ADM_UC01
Admin -- ADM_UC02
Admin -- ADM_UC20
Admin -- ADM_UC04
Admin -- ADM_UC05
Admin -- ADM_UC06
Admin -- ADM_UC07
Admin -- ADM_UC08
Admin -- ADM_UC09
Admin -- ADM_UC10
Admin -- ADM_UC11
Admin -- ADM_UC12
Admin -- ADM_UC13
Admin -- ADM_UC14
Admin -- ADM_UC15
Admin -- ADM_UC16
Admin -- ADM_UC17
Admin -- ADM_UC18
Admin -- ADM_UC19

ADM_UC19 ..> ADM_UC18 : <<include>>

@enduml
